Update mac appcontainer install script.

diff --git a/install_appcontainer_mac b/install_appcontainer_mac
--- a/install_appcontainer_mac
+++ b/install_appcontainer_mac
@@ -1,4 +1,9 @@
 #!/bin/bash
+cd -- "$(dirname -- "$0")" || {
+  echo "Unable to change to script directory." >&2
+  exit 1
+}
+
 bash scripts/certs
 docker compose pull
 docker compose up -d
